name: Freqtrade TUI CI

on:
  push:
    branches:
      - main
      - ci/*
  release:
    types: [published]
  pull_request:

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}-${{ github.event_name }}"
  cancel-in-progress: true
permissions:
  repository-projects: read



jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ "ubuntu-20.04", "ubuntu-22.04", "macos-12", "macos-13", "macos-14", "windows-latest" ]
        python-version: ["3.9", "3.10", "3.11", "3.12"]

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install .
        pip install ruff

    - name: Test execution (for now with `--help`)
      run: |
        ftui --help

    - name: Run Ruff
      run: |
        ruff check --output-format=github

    # - name: Run Ruff format check
    #   run: |
    #     ruff format --check

  publish:
    name: "Deploy to pypi"
    if: (github.event_name == 'release')
    environment:
      name: release
      url: https://pypi.org/p/ftui

    permissions:
      id-token: write

    needs: build
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"


    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install build


    - name: Build package
      run: |
        pip install -U build
        python -m build

    - name: Publish to PyPI (Test)
      uses: pypa/gh-action-pypi-publish@v1.8.14
      with:
        repository-url: https://test.pypi.org/legacy/

    - name: Publish to PyPI
      uses: pypa/gh-action-pypi-publish@v1.8.14
